import { readFileSync } from 'node:fs';
import { transferPayload } from '../skills/woia-re-property-acquisition/scripts/evaluate-acquisition.mjs';
export const bindings = JSON.parse(readFileSync(new URL('../skills/woia-re-property-acquisition/references/release-bindings.json', import.meta.url)));
export function fixture(service = 'sale', mode = 'next-action') {
  const request = { task_ref: 'task:intake', organization_ref: 'org:synthetic', actor_ref: 'person:operator', property_ref: 'property:one', unit_ref: null, principal_ref: 'person:owner', purpose: 'accepted-service-intake', scope_version: 'v1', service, services: [service], mode, next_action: mode === 'prepare' ? 'prepare-permitted-inputs' : mode === 'transfer' ? 'propose-transfer' : 'evaluate-next-action', source_map_revision: 'sam:v1', idempotency_key: 'intake:one:v1', snapshot_ref: 'core-snapshot:one' };
  const scope = Object.fromEntries(['organization_ref', 'actor_ref', 'property_ref', 'unit_ref', 'principal_ref', 'purpose', 'scope_version', 'service'].map(k => [k, request[k]]));
  const validity = { current: true, revoked: false, hold: false, valid_from: 0, valid_until: 200 };
  const kinds = mode === 'prepare' ? [] : ['representation', 'mandate', 'accepted-terms', ...(service === 'existing-lease-administration' ? ['existing-lease', 'participants', 'responsibilities', 'documents', 'source-cutover'] : ['offering-inputs'])];
  const host = { now: 100, scope: { ...scope, services: request.services }, source_map_revision: request.source_map_revision, snapshot_ref: request.snapshot_ref, core_release: structuredClone(bindings.core), base_release: structuredClone(bindings.base), action: { ...scope, ...validity, next_action: request.next_action, mode, policy_ref: 'policy:synthetic:v1', competent_owner: 'competent:synthetic', requirements: kinds, requires_mandate: mode !== 'prepare', department: 'supply-acquisition', effect_class: 'NONE' }, grant: { ...scope, ...validity, next_action: request.next_action, decision_ref: 'decision:one', owner: 'competent:synthetic', status: 'ACCEPTED', source_map_revision: request.source_map_revision }, facts: kinds.map(kind => ({ ...scope, ...validity, next_action: request.next_action, kind, ref: `evidence:${kind}`, version: 'v1', source_ref: `source:${kind}`, source_map_revision: request.source_map_revision, status: 'ACCEPTED', accepted_by: 'competent:synthetic', decision_ref: `decision:${kind}`, disputed: false, lifecycle: 'ACTIVE' })), source_rules: kinds.map(kind => ({ ...scope, ...validity, kind, source_map_revision: request.source_map_revision, source_ref: `source:${kind}`, competent_owner: 'competent:synthetic' })), contributions: [], continuity: { ...scope, owner: 'supply-acquisition', review_ref: 'due-work:review', snapshot_ref: request.snapshot_ref }, effect_status: 'NONE', transfer: { ...scope, ...validity, receiver: { sale: 'sales', 'rental-placement': 'leasing', 'existing-lease-administration': 'asset-management' }[service], accepted_by: { sale: 'sales', 'rental-placement': 'leasing', 'existing-lease-administration': 'asset-management' }[service], status: 'ACCEPTED', acceptance_ref: 'acceptance:transfer', source_ref: 'source:transfer', snapshot_ref: request.snapshot_ref } };
  const base = { result: 'NEXT_ACTION_ELIGIBLE', task_ref: request.task_ref, subject_ref: request.property_ref, service, next_action: request.next_action, source_map_revision: request.source_map_revision, idempotency_key: request.idempotency_key, dispatch_performed: false, fact_written: false, authority_granted: false };
  host.emergency_stop = false;
  host.transfer_acceptance = { ...validity, ref: host.transfer.acceptance_ref, source_ref: host.transfer.source_ref, accepted_by: host.transfer.receiver, status: 'ACCEPTED', version: 'v1', accepted_payload: transferPayload(request, host) };
  return { request, host, base };
}
export function contribution(f) {
  return { ...f.host.scope, current: true, revoked: false, hold: false, valid_from: 0, valid_until: 200, request_ref: 'core-request:one', origin_task_ref: f.request.task_ref, receiver_task_ref: 'task:receiver', next_action: f.request.next_action, receiver: 'operations', accepted_by: 'operations', distinct_outcome: true, objective: 'accepted distinct field evidence', shared_ref: 'property:one', status: 'ACCEPTED_RESULT', response_ref: 'core-response:one', acceptance_ref: 'acceptance:receiver', snapshot_ref: f.request.snapshot_ref };
}
